version: '3'
services:
  app:
    image: app
    build: ./front-end
    ports:
      - '80:80'
      - '443:443'

    networks:
      - notiefi

  api:
    image: api
    build: ./back-end
    ports:
      - '3001:3001'
    networks:
      - notiefi

networks:
  notiefi:
    driver: bridge
